version: "3"

dotenv:
  - .env

tasks:
  run:api:
    desc: Run the API server locally
    cmds:
      - go run ./cmd/api

  migrate:up:
    desc: Apply all pending database migrations
    cmds:
      - migrate -path sql/migrations -database "$DATABASE_URL" up

  migrate:down:
    desc: Roll back the latest database migration
    cmds:
      - migrate -path sql/migrations -database "$DATABASE_URL" down 1

  migrate:create:
    desc: Create a new database migration. Usage) task migrate:create -- init
    cmds:
      - migrate create -ext sql -dir sql/migrations -seq {{.CLI_ARGS}}

  sqlc:generate:
    desc: Generate Go code from SQL queries
    cmds:
      - sqlc generate

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  docker:up:
    desc: Start Docker Compose services
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop Docker Compose services
    cmds:
      - docker compose down
